# Generated by Django 5.2.5 on 2025-09-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_user_shares_note_shared_with"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="shares",
            name="can_modify",
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shares",
            name="permissions",
            field=models.ManyToManyField(to="notes.permissions"),
        ),
    ]
