# Generated by Django 5.2.5 on 2025-09-26 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_permissions_remove_shares_can_modify_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="user",
            new_name="owner",
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share",
                        to="notes.note",
                    ),
                ),
                ("permissions", models.ManyToManyField(to="notes.permissions")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="note",
            name="shared_with",
            field=models.ManyToManyField(
                through="notes.Share", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Shares",
        ),
    ]
