# Generated by Django 5.2.5 on 2025-09-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_rename_user_note_owner_share_alter_note_shared_with_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="shared_with",
            new_name="shares",
        ),
    ]
