# Generated by Django 5.2.5 on 2025-09-27 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_rename_shared_with_note_shares"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="share",
            constraint=models.UniqueConstraint(
                fields=("user", "note"), name="unique_share_per_user_per_note"
            ),
        ),
    ]
