# Generated by Django 5.2.5 on 2025-09-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_share_unique_share_per_user_per_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="shares",
        ),
    ]
