# Generated by Django 5.2.6 on 2025-10-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_remove_note_shares"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="share",
            name="unique_share_per_user_per_note",
        ),
        migrations.AlterField(
            model_name="share",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="notes.note"
            ),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.UniqueConstraint(fields=("user", "note"), name="unique_share_per_user"),
        ),
    ]
