# Generated by Django 5.2.6 on 2025-10-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_share_unique_share_per_user_per_note_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='NotePermissions',
        ),
    ]
