# Generated by Django 5.2.6 on 2025-10-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_rename_permissions_notepermissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotePermissions',
            new_name='NotePermission',
        ),
    ]
