# Generated by Django 5.2.5 on 2025-11-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0010_rename_notepermissions_notepermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="share",
            name="permissions",
        ),
        migrations.AddField(
            model_name="share",
            name="role",
            field=models.CharField(
                choices=[("viewer", "Viewer"), ("editor", "Editor")],
                default="viewer",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="NotePermission",
        ),
    ]
